### ISSUE TITLE
Cannot find module '..\build\Release\pty.node'

### ISSUE THREAD

**Issue by DavideCarvalho** [matthew-matvei/freeman#5]
I tried to build the app on Windows, but gives me this error:
```(node:7044) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: Service Unavailable
(node:7044) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
$ electron app/main.js

App threw an error during load
Error: Cannot find module '..\build\Release\pty.node'
    at Module._resolveFilename (module.js:485:15)
    at Function.Module._resolveFilename (C:\Users\davi.carvalho\Documents\freeman\node_modules\electron\dist\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\davi.carvalho\Documents\freeman\node_modules\node-pty\lib\windowsPtyAgent.js:9:11)
    at Object.<anonymous> (C:\Users\davi.carvalho\Documents\freeman\node_modules\node-pty\lib\windowsPtyAgent.js:167:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)```

I used yarn install to install the dependencies and yarn start to start the app

**Comment by matthew-matvei** [comment]
Hmm, I wasn't able to reproduce this when doing `yarn install` -> `yarn start`.

Can you confirm that this occurs in latest `master` branch. As part of looking into this, I have noticed that `develop` branch has missed out on a fix that ought to be there, which I will certainly rectify.

Are you able to successfully `npm install` -> `npm run start`?

**Comment by matthew-matvei** [comment]
`npm install && npm start` is what the AppVeyor build server using each build, I can't replicate this using `yarn install && yarn start`, so I'm closing this down for now.
